# config.toml
baseURL = 'https://prlosana.github.io/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Dr. Anasol Peña-Rios'
theme = 'PaperMod'

# Enable features
enableGitInfo = false
enableEmoji = true
enableRobotsTXT = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats for search
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Main sections (for home page) - empty to prevent posts on home page
mainSections = []

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "bio"
    name = "About Me"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20
  [[menu.main]]
    identifier = "leadership"
    name = "Leadership & Volunteering"
    url = "/leadership/"
    weight = 30
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 60
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 70

# PaperMod theme configuration
[params]
  # Site description
  description = "Dr. Anasol Peña-Rios"
  
  # Default theme mode
  defaultTheme = "auto"

  # To Hide meta elements : date, read-time, author and available-translations for page
  hideMeta = true
  
  # Show reading time
  ShowReadingTime = false
  
  # Show word count
  ShowWordCount = false
  
  # Show table of contents
  ShowToc = false
  
  # Enable code copy button
  ShowCodeCopyButtons = true
  
  # Enable social icons
  ShowShareButtons = false
  
  # Enable search
  ShowSearch = true
  
  # Search configuration
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
  
  # Enable comments
  ShowComments = false
  
  # Enable related content
  ShowRelatedContent = false
  
  # Enable breadcrumbs
  ShowBreadCrumbs = true
  
  # Enable last modified
  ShowLastMod = false
  
  # Enable author
  ShowAuthor = false
  
  # Enable date
  ShowDate = false
  
  # Enable categories
  ShowCategories = true
  
  # Enable tags
  ShowTags = true
  
  # Enable taxonomies
  ShowTaxonomies = true
  
  # Enable archive
  ShowArchive = true
  
  # Enable social icons in profile mode
  ShowSocialIcons = true
  
  # Hide the "Powered by Hugo & PaperMod" footer
  ShowPoweredBy = false
  
  # Enable profile mode
  [params.profileMode]
    enabled = false

# Social icons
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/prlosana"
[[params.socialIcons]]
  name = "linkedin"
  url = "http://uk.linkedin.com/in/prlosana"
[[params.socialIcons]]
  name = "email"
  url = "mailto:acpena@ieee.org"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    noHl = false
    style = "github"
    tabWidth = 4
    lineNos = true
    lineNumbersInTable = true
    guessSyntax = true

# Permalinks
[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"
  pages = "/:slug/"
